"""init

Revision ID: ccf69d3fc258
Revises: dd33cb03d01f
Create Date: 2023-07-18 16:10:07.986432

"""

# revision identifiers, used by Alembic.
revision = 'ccf69d3fc258'
down_revision = 'dd33cb03d01f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
