"""init

Revision ID: f0a01e793213
Revises: ccf69d3fc258
Create Date: 2023-07-19 11:10:55.061648

"""

# revision identifiers, used by Alembic.
revision = 'f0a01e793213'
down_revision = 'ccf69d3fc258'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
